package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopdf/internal/actions"
	"gopdf/internal/config"
	"gopdf/internal/viewer"
)

func main() {
	check := flag.Bool("check", false, "check generated files without writing")
	flag.Parse()
	if err := config.ValidateReferenceMetadata(); err != nil {
		fatal(err)
	}
	outputs := map[string][]byte{
		"docs/reference.md":  []byte(renderReference()),
		"config.example.lua": []byte(renderExampleConfig()),
	}
	for path, content := range outputs {
		if *check {
			existing, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(existing, content) {
				fatal(fmt.Errorf("%s is stale; run go generate ./...", path))
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fatal(err)
		}
	}
}

func renderReference() string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by go generate ./...; DO NOT EDIT. -->\n\n")
	b.WriteString("# gopdf Reference\n\n")
	b.WriteString("This reference is generated from the registries used by the application.\n\n")
	b.WriteString("## Configuration Options\n\n")
	b.WriteString("Options can be assigned with `gopdf.options.<name> = <value>` in Lua or `:set <name>=<value>` at runtime. Colors use `{ r, g, b }` in Lua and `r,g,b` or `#RRGGBB` with `:set`.\n\n")
	b.WriteString("| Option | Type | Default | Description |\n|---|---|---|---|\n")
	for _, ref := range config.OptionReferences() {
		fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s |\n", ref.Name, ref.Type, escapeCell(ref.Default), ref.Description)
	}

	b.WriteString("\n## Commands\n\n")
	b.WriteString("| Command | Description |\n|---|---|\n")
	for _, ref := range viewer.CommandReferences() {
		fmt.Fprintf(&b, "| `%s` | %s |\n", ref.Command, ref.Description)
	}
	b.WriteString("\nSearch flags: `-r` regular expression, `-i` ignore case, `-w` whole word, and `-p` current page only. Flags can be combined.\n")

	b.WriteString("\n## Lua Functions\n\n")
	b.WriteString("| Function | Description |\n|---|---|\n")
	for _, ref := range config.LuaReferences() {
		fmt.Fprintf(&b, "| `%s` | %s |\n", ref.Signature, ref.Description)
	}

	b.WriteString("\n## Bindable Actions\n\n")
	b.WriteString("Every action is available as `gopdf.<action>`, can be passed to `gopdf.bind`, and can be called from a runtime Lua callback.\n\n")
	b.WriteString("| Action | Default keys | Countable |\n|---|---|---|\n")
	for _, action := range actions.All() {
		keys := ""
		if len(action.Keys) > 0 {
			quoted := make([]string, len(action.Keys))
			for i, key := range action.Keys {
				quoted[i] = "`" + displayKey(key) + "`"
			}
			keys = strings.Join(quoted, ", ")
		}
		fmt.Fprintf(&b, "| `%s` | %s | %t |\n", action.Name, keys, action.Countable)
	}

	b.WriteString("\n## Lua Tables\n\n")
	b.WriteString("- `gopdf.document`: `path`, `name`, `extension`, `exists`, `size_bytes`, and `page_count`.\n")
	b.WriteString("- `gopdf.status_bar`: `left`, `right`, `height`, and `visible`.\n")
	b.WriteString("- `gopdf.options`: all entries from the configuration-options table above.\n")
	b.WriteString("- `gopdf.cache` and `gopdf.ui`: functions are listed in the Lua-functions table.\n")
	return b.String()
}

func renderExampleConfig() string {
	var b strings.Builder
	b.WriteString("-- Code generated by go generate ./...; DO NOT EDIT.\n")
	b.WriteString("-- All supported options and default bindings. Copy only values you want to change.\n\n")
	for _, ref := range config.OptionReferences() {
		fmt.Fprintf(&b, "gopdf.options.%s = %s -- %s\n", ref.Name, ref.Default, ref.Description)
	}
	b.WriteString("\n-- Default key bindings.\n\n")
	for _, action := range actions.All() {
		for _, key := range action.Keys {
			fmt.Fprintf(&b, "gopdf.bind(%q, gopdf.%s)\n", key, action.Name)
		}
	}
	b.WriteString("\n-- Default mouse bindings.\n\n")
	cfg := config.Default()
	events := make([]string, 0, len(cfg.MouseBindings))
	for event := range cfg.MouseBindings {
		events = append(events, event)
	}
	sort.Strings(events)
	for _, event := range events {
		fmt.Fprintf(&b, "gopdf.bind_mouse(%q, gopdf.%s)\n", event, cfg.MouseBindings[event])
	}
	return b.String()
}

func displayKey(key string) string {
	if key == " " {
		return "Space"
	}
	return key
}

func escapeCell(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
