-- Code generated by go generate ./...; DO NOT EDIT.
-- All supported options and default bindings. Copy only values you want to change.

gopdf.options.alt_background = {20, 20, 20} -- Viewer background in alternate-color mode.
gopdf.options.alt_colors = false -- Start with alternate colors enabled.
gopdf.options.alt_foreground = {255, 255, 255} -- UI foreground in alternate-color mode.
gopdf.options.alt_page_background = {17, 17, 17} -- Page background in alternate-color mode.
gopdf.options.alt_status_bar_color = {20, 20, 20} -- Status bar background in alternate-color mode.
gopdf.options.anchor_position = "center" -- Viewport anchor: center, top, or bottom.
gopdf.options.anti_aliasing = 8 -- MuPDF antialiasing level from 0 through 8.
gopdf.options.background = {220, 220, 220} -- Viewer background color.
gopdf.options.completion_max_items = 10 -- Maximum command-completion rows.
gopdf.options.dual_page = false -- Start in dual-page mode.
gopdf.options.first_page_offset = true -- Treat the first page as a standalone cover in dual-page mode.
gopdf.options.fit_mode = "page" -- Initial fit mode: page, width, or manual.
gopdf.options.foreground = {20, 20, 20} -- UI foreground color.
gopdf.options.highlight_background = {255, 224, 102} -- Selection and search highlight background.
gopdf.options.highlight_foreground = {0, 0, 0} -- Selection and search highlight border and text.
gopdf.options.mouse_text_select = true -- Enable text selection with the left mouse button.
gopdf.options.natural_scroll = false -- Reverse mouse-wheel scrolling direction.
gopdf.options.outline_height_percent = 80 -- Outline overlay height as a percentage of the window.
gopdf.options.outline_initial_depth = 1 -- Outline levels expanded when the outline opens.
gopdf.options.outline_width_percent = 70 -- Outline overlay width as a percentage of the window.
gopdf.options.page_background = {255, 255, 255} -- Normal page background color.
gopdf.options.page_cache_size = 16 -- Maximum rendered pages retained in the cache.
gopdf.options.page_gap = 0 -- Vertical gap between pages; aliases page_gap_vertical.
gopdf.options.page_gap_horizontal = 0 -- Horizontal gap between pages in a spread.
gopdf.options.page_gap_vertical = 0 -- Vertical gap between page rows.
gopdf.options.recent_files_max = 20 -- Maximum recent files retained and displayed.
gopdf.options.render_mode = "continuous" -- Initial render mode: continuous or single.
gopdf.options.render_oversample = 1 -- Render scale multiplier; values above 1 supersample.
gopdf.options.scroll_step = 64 -- Keyboard and mouse scroll distance in pixels.
gopdf.options.sequence_timeout_ms = 700 -- Maximum delay between keys in a binding sequence.
gopdf.options.session_database = true -- Persist per-document view state, marks, and recent files.
gopdf.options.spread_gap = 0 -- Horizontal spread gap; aliases page_gap_horizontal.
gopdf.options.status_bar_color = {220, 220, 220} -- Normal status bar background color.
gopdf.options.status_bar_height = 28 -- Status bar height in pixels.
gopdf.options.status_bar_left = "{message}" -- Left status bar template.
gopdf.options.status_bar_padding = 8 -- Horizontal status bar padding in pixels.
gopdf.options.status_bar_right = "{page}/{total} {mode} fit={fit} rot={rot} {zoom}" -- Right status bar template.
gopdf.options.status_bar_visible = true -- Show the status bar at startup.
gopdf.options.ui_font_path = "" -- Path to a UI font; empty uses the built-in default.
gopdf.options.ui_font_size = 14 -- UI font size in pixels.

-- Default key bindings.

gopdf.bind("J", gopdf.next_page)
gopdf.bind(" ", gopdf.next_page)
gopdf.bind("<PgDn>", gopdf.next_page)
gopdf.bind("K", gopdf.prev_page)
gopdf.bind("<PgUp>", gopdf.prev_page)
gopdf.bind("j", gopdf.scroll_down)
gopdf.bind("<Down>", gopdf.scroll_down)
gopdf.bind("k", gopdf.scroll_up)
gopdf.bind("<Up>", gopdf.scroll_up)
gopdf.bind("h", gopdf.scroll_left)
gopdf.bind("<Left>", gopdf.scroll_left)
gopdf.bind("l", gopdf.scroll_right)
gopdf.bind("<Right>", gopdf.scroll_right)
gopdf.bind("gg", gopdf.first_page)
gopdf.bind("G", gopdf.last_page)
gopdf.bind(":", gopdf.command_mode)
gopdf.bind("/", gopdf.search_prompt)
gopdf.bind("?", gopdf.search_prompt_backward)
gopdf.bind("n", gopdf.search_next)
gopdf.bind("N", gopdf.search_prev)
gopdf.bind("d", gopdf.toggle_dual_page)
gopdf.bind("m", gopdf.toggle_render_mode)
gopdf.bind("<C-r>", gopdf.toggle_alt_colors)
gopdf.bind("co", gopdf.toggle_first_page_offset)
gopdf.bind("<C-n>", gopdf.toggle_status_bar)
gopdf.bind("f", gopdf.toggle_fullscreen)
gopdf.bind("o", gopdf.outline)
gopdf.bind("<CR>", gopdf.confirm)
gopdf.bind("+", gopdf.zoom_in)
gopdf.bind("=", gopdf.zoom_in)
gopdf.bind("-", gopdf.zoom_out)
gopdf.bind("0", gopdf.reset_zoom)
gopdf.bind("w", gopdf.fit_width)
gopdf.bind("z", gopdf.fit_page)
gopdf.bind("<C-S-r>", gopdf.reload_config)
gopdf.bind("r", gopdf.rotate_cw)
gopdf.bind("R", gopdf.rotate_ccw)
gopdf.bind("<C-g>", gopdf.goto_page_prompt)
gopdf.bind("<Tab>", gopdf.show_completion)
gopdf.bind("<S-Tab>", gopdf.prev_completion)
gopdf.bind("<Esc>", gopdf.close)
gopdf.bind("<C-i>", gopdf.jump_forward)
gopdf.bind("<C-o>", gopdf.jump_backward)
gopdf.bind("<C-S-o>", gopdf.open_file_picker)
gopdf.bind("gr", gopdf.show_recent_files)
gopdf.bind("<F1>", gopdf.keybinds)
gopdf.bind("q", gopdf.quit)

-- Default mouse bindings.

gopdf.bind_mouse("<c-wheel_down>", gopdf.zoom_out)
gopdf.bind_mouse("<c-wheel_up>", gopdf.zoom_in)
gopdf.bind_mouse("middle_down", gopdf.pan)
gopdf.bind_mouse("wheel_down", gopdf.scroll_down)
gopdf.bind_mouse("wheel_left", gopdf.scroll_left)
gopdf.bind_mouse("wheel_right", gopdf.scroll_right)
gopdf.bind_mouse("wheel_up", gopdf.scroll_up)
