-- Code generated by go generate ./...; DO NOT EDIT.
-- All supported options and default bindings. Copy only values you want to change.

gopdf.options.alt_colors = false -- Start with alternate colors: true, false, or "system" to follow the OS's dark mode as it changes.
gopdf.options.alt_colors_keep_images = true -- Keep raster images in their own colors in alternate-color mode.
gopdf.options.anchor_position = "center" -- Viewport anchor: center, top, or bottom.
gopdf.options.animation_frame_ms = 0 -- Animation timestep in milliseconds; 0 follows the display's refresh rate.
gopdf.options.annotation_colors = {"#ffe066", "#8ce99a", "#74c0fc", "#ffa8a8"} -- Highlight colours offered by the highlight picker, as #RRGGBB.
gopdf.options.anti_aliasing = 8 -- MuPDF antialiasing level from 0 through 8.
gopdf.options.auto_reload = true -- Reload the document when its file changes on disk.
gopdf.options.auto_reload_delay_ms = 200 -- Milliseconds a changed file must stay unwritten before it reloads, so a file being written reloads once.
gopdf.options.autoscroll_max_speed = 20000 -- Fastest autoscroll speed in pixels per second, however far the pointer is from the anchor; 0 or less removes the limit.
gopdf.options.autoscroll_speed_factor = 1 -- Multiplier for autoscroll speed at every pointer distance from the anchor, up to autoscroll_max_speed; clamped to at least 0.01.
gopdf.options.completion_max_items = 10 -- Maximum command-completion rows.
gopdf.options.copy_on_select = true -- Copy selected text to the clipboard when the mouse selection is released.
gopdf.options.dual_page = false -- Start in dual-page mode.
gopdf.options.first_page_offset = true -- Treat the first page as a standalone cover in dual-page mode.
gopdf.options.fit_mode = "page" -- Initial fit mode: page, width, height, or manual.
gopdf.options.hint_chars = "asdfghjkl" -- Characters used for link hint labels, in order of preference.
gopdf.options.invert_scroll = false -- Invert horizontal and vertical discrete mouse-wheel scrolling.
gopdf.options.invert_smooth_scroll = false -- Invert horizontal and vertical smooth wheel or trackpad scrolling.
gopdf.options.link_preview = true -- Preview the destination of an internal link after hovering it briefly.
gopdf.options.link_preview_delay_ms = 400 -- Milliseconds to hover an internal link before its preview appears.
gopdf.options.link_schemes = {"http", "https", "mailto"} -- URI schemes that document links may open externally; other links only show their target.
gopdf.options.loading_indicator = true -- Animate a loading indicator on pages still rendering for the first time.
gopdf.options.max_zoom = 8 -- Maximum manual zoom scale.
gopdf.options.min_zoom = 0.5 -- Minimum manual zoom scale.
gopdf.options.mouse_text_select = true -- Enable text selection with the left mouse button.
gopdf.options.mupdf_store_mb = 256 -- MuPDF cache for fonts and decoded images in MiB; applies to newly opened documents.
gopdf.options.outline_height_percent = 80 -- Outline overlay height as a percentage of the window.
gopdf.options.outline_initial_depth = 1 -- Outline levels expanded when the outline opens.
gopdf.options.outline_width_percent = 70 -- Outline overlay width as a percentage of the window.
gopdf.options.overview_gap = 16 -- Gap in pixels between the page overview's cells.
gopdf.options.overview_max_columns = 12 -- Most columns the page overview shows, whether fitted to the window or set with zoom_out.
gopdf.options.overview_thumb_width = 220 -- Width in pixels the page overview aims to show each page at, which sets how many columns fit.
gopdf.options.page_cache_memory_mb = 512 -- Maximum memory in MiB for cached page renders; 0 disables the limit.
gopdf.options.page_cache_size = 0 -- Deprecated and ignored; the cache is bounded by page_cache_memory_mb.
gopdf.options.page_gap = 0 -- Vertical gap between pages; aliases page_gap_vertical.
gopdf.options.page_gap_horizontal = 0 -- Horizontal gap between pages in a spread.
gopdf.options.page_gap_vertical = 0 -- Vertical gap between page rows.
gopdf.options.pinch_sensitivity = 1 -- Trackpad pinch zoom sensitivity; 1 preserves the gesture scale.
gopdf.options.prompt_history_max = 100 -- Maximum entries kept in each of the command and search prompt histories; 0 keeps none.
gopdf.options.recent_files_max = 20 -- Maximum recent files retained and displayed.
gopdf.options.render_mode = "continuous" -- Initial render mode: continuous or single.
gopdf.options.render_oversample = 1 -- Render scale multiplier; values above 1 supersample.
gopdf.options.render_threads = 0 -- Page rendering threads; 0 picks one per core up to 4, leaving a core free. Applies to newly opened documents.
gopdf.options.scroll_off = 1 -- Minimum number of rows kept visible above and below the selected item in UI menus, like Vim's scrolloff.
gopdf.options.scroll_step = 64 -- Keyboard and mouse scroll distance in pixels.
gopdf.options.sequence_timeout_ms = 700 -- Maximum delay between keys in a binding sequence.
gopdf.options.session_database = true -- Persist per-document view state, marks, and recent files.
gopdf.options.smooth_scroll = { mouse = true, trackpad = true, keyboard = true } -- Animate scrolling for selected inputs; assignments update only specified mouse, trackpad, and keyboard fields.
gopdf.options.smooth_scroll_dampening = 0.8 -- Catch-up factor for smooth scrolling per animation frame; higher values are more responsive and less damped; clamped to 0.01 through 1.
gopdf.options.smooth_zoom = { mouse = true, trackpad = true, keyboard = true } -- Animate zooming for selected inputs; assignments update only specified mouse, trackpad, and keyboard fields.
gopdf.options.smooth_zoom_dampening = 0.8 -- Catch-up factor for smooth zooming per animation frame; higher values are more responsive and less damped; clamped to 0.01 through 1.
gopdf.options.spread_gap = 0 -- Horizontal spread gap; aliases page_gap_horizontal.
gopdf.options.status_bar_left = "{modified}{message}" -- Left status bar template.
gopdf.options.status_bar_right = "{page}/{total} {mode} fit={fit} rot={rot} {zoom}" -- Right status bar template.
gopdf.options.status_bar_visible = true -- Show the status bar.
gopdf.options.trim_margins = false -- Lay pages out by their content, trimming blank margins.
gopdf.options.trim_padding = 8 -- Margin in points kept around a page's content when trimming margins.
gopdf.options.zoom_step = 1.15 -- Factor zoom_in multiplies the zoom by, and zoom_out divides it by; above 1.

-- The theme. Fields left out keep the values of the base theme.

gopdf.theme = {
  base = "moss",
  background = "#e6e4dd", -- Canvas behind the pages.
  page = "#ffffff", -- Paper of pages still rendering.
  foreground = "#2a2e29", -- UI text.
  muted = "#737a70", -- Secondary UI text, such as menu details and the right of the status bar.
  accent = "#4d7044", -- Prompts, link hints, headings, the selected menu row's ribbon and the overview's selected page.
  panel = "#fbfaf7", -- Background of menus, completion and other panels.
  border = "#d5d2c9", -- Hairlines around panels and above the status bar.
  status_bar = "#f1f0eb", -- Status bar background.
  selection = "#bfd9a9", -- Highlight of selected text.
  search = "#f2dc8c", -- Highlight of search matches.
  search_current = "#eaa660", -- Highlight of the current search match.
  hint_foreground = "#fbfaf7", -- Text of link hints, set on the accent.
  presentation = "#0f110f", -- Background around the page in presentation mode.
  alt = {
    background = "#121412", -- Canvas behind the pages in alternate-color mode.
    page = "#1f2420", -- Paper of pages still rendering, and of pages recoloured in alternate-color mode.
    foreground = "#d9dfd4", -- UI text, and the ink of pages recoloured in alternate-color mode.
    muted = "#8b9487", -- Secondary UI text, such as menu details and the right of the status bar in alternate-color mode.
    accent = "#9dc48b", -- Prompts, link hints, headings, the selected menu row's ribbon and the overview's selected page in alternate-color mode.
    panel = "#232823", -- Background of menus, completion and other panels in alternate-color mode.
    border = "#363c35", -- Hairlines around panels and above the status bar in alternate-color mode.
    status_bar = "#1c1f1c", -- Status bar background in alternate-color mode.
    selection = "#4f6b45", -- Highlight of selected text in alternate-color mode.
    search = "#7a6a32", -- Highlight of search matches in alternate-color mode.
    search_current = "#9a6430", -- Highlight of the current search match in alternate-color mode.
    hint_foreground = "#1c1f1c", -- Text of link hints, set on the accent in alternate-color mode.
    presentation = "#0f110f", -- Background around the page in presentation mode in alternate-color mode.
  },
  font = {
    family = "", -- Installed UI font family; empty uses the system interface font, such as SF on macOS or Segoe UI on Windows.
    path = "", -- UI font file; overrides font.family, font.style and font.weight.
    size = 13, -- UI font size in logical pixels, scaled up on high-density displays.
    weight = 400, -- UI font weight as CSS number 100-900 or alias such as normal, medium, semibold, bold, or black.
    style = "normal", -- UI font style: normal, italic, or oblique.
  },
  radius = 3, -- Corner radius of panels, menu rows and the status pill in logical pixels; 0 gives square corners.
  padding = 8, -- Space around UI text in menu rows, panels and the status bar, in logical pixels.
  shadow = true, -- Draw a soft shadow under floating panels.
  status_bar_style = "bar", -- Status bar layout: bar along the bottom of the window, or pill, floating over the page.
  status_bar_padding = 10, -- Horizontal status bar padding in logical pixels.
  motion = {
    scale = 1, -- Speed of every transition: 1 as given, 2 twice as slow, 0 for no motion at all, as when the OS is set to reduce motion.
    panel = "none", -- Menus and completion fading in as they open, and menus fading out as they close.
    selection = "80ms ease-out", -- The selected row's highlight gliding to the next row selected.
    prompt = "100ms ease-out", -- The sides of the status bar growing and shrinking with their text, as a pill does when a prompt opens.
    message = "none", -- Status messages fading in, and out when cleared.
    cursor = "50ms ease-out", -- The prompt's cursor gliding to where it moves.
  },
  elements = {}, -- The style of each piece of the UI, such as panel or row_selected; see Elements in the reference.
}

-- Default key bindings.

gopdf.bind("J", gopdf.next_page)
gopdf.bind("<PgDn>", gopdf.next_page)
gopdf.bind("K", gopdf.prev_page)
gopdf.bind("<PgUp>", gopdf.prev_page)
gopdf.bind("j", gopdf.scroll_down)
gopdf.bind("<Down>", gopdf.scroll_down)
gopdf.bind("k", gopdf.scroll_up)
gopdf.bind("<Up>", gopdf.scroll_up)
gopdf.bind("h", gopdf.scroll_left)
gopdf.bind("<Left>", gopdf.scroll_left)
gopdf.bind("l", gopdf.scroll_right)
gopdf.bind("<Right>", gopdf.scroll_right)
gopdf.bind("gg", gopdf.first_page)
gopdf.bind("G", gopdf.last_page)
gopdf.bind(":", gopdf.command_mode)
gopdf.bind("/", gopdf.search_prompt)
gopdf.bind("?", gopdf.search_prompt_backward)
gopdf.bind("n", gopdf.search_next)
gopdf.bind("N", gopdf.search_prev)
gopdf.bind("d", gopdf.toggle_dual_page)
gopdf.bind("m", gopdf.toggle_render_mode)
gopdf.bind("<C-r>", gopdf.toggle_alt_colors)
gopdf.bind("co", gopdf.toggle_first_page_offset)
gopdf.bind("ct", gopdf.toggle_trim_margins)
gopdf.bind("<C-n>", gopdf.toggle_status_bar)
gopdf.bind("f", gopdf.toggle_fullscreen)
gopdf.bind("<F5>", gopdf.presentation)
gopdf.bind("F", gopdf.follow_link)
gopdf.bind("o", gopdf.outline)
gopdf.bind("O", gopdf.overview)
gopdf.bind("<CR>", gopdf.confirm)
gopdf.bind("+", gopdf.zoom_in)
gopdf.bind("=", gopdf.zoom_in)
gopdf.bind("-", gopdf.zoom_out)
gopdf.bind("0", gopdf.reset_zoom)
gopdf.bind("a", gopdf.fit_width)
gopdf.bind("s", gopdf.fit_page)
gopdf.bind("S", gopdf.fit_height)
gopdf.bind("<C-S-r>", gopdf.reload_config)
gopdf.bind("r", gopdf.rotate_cw)
gopdf.bind("R", gopdf.rotate_ccw)
gopdf.bind("<C-g>", gopdf.goto_page_prompt)
gopdf.bind("H", gopdf.highlight_selection)
gopdf.bind("u", gopdf.undo)
gopdf.bind("U", gopdf.redo)
gopdf.bind("x", gopdf.delete_annotation)
gopdf.bind("gm", gopdf.search_matches)
gopdf.bind("<Tab>", gopdf.show_completion)
gopdf.bind("<S-Tab>", gopdf.prev_completion)
gopdf.bind("<C-c>", gopdf.copy)
gopdf.bind("<C-x>", gopdf.cut)
gopdf.bind("<C-v>", gopdf.paste)
gopdf.bind("<Esc>", gopdf.close)
gopdf.bind("<C-i>", gopdf.jump_forward)
gopdf.bind("<C-o>", gopdf.jump_backward)
gopdf.bind("<C-S-o>", gopdf.open_file_picker)
gopdf.bind("gr", gopdf.show_recent_files)
gopdf.bind("<F1>", gopdf.help)
gopdf.bind("g?", gopdf.help)
gopdf.bind("<Space>", gopdf.pan)
gopdf.bind("q", gopdf.quit)

-- Default mouse bindings.

gopdf.bind_mouse("<C-wheel_down>", gopdf.zoom_out)
gopdf.bind_mouse("<C-wheel_up>", gopdf.zoom_in)
gopdf.bind_mouse("middle_down", gopdf.autoscroll)
gopdf.bind_mouse("wheel_down", gopdf.scroll_down)
gopdf.bind_mouse("wheel_left", gopdf.scroll_left)
gopdf.bind_mouse("wheel_right", gopdf.scroll_right)
gopdf.bind_mouse("wheel_up", gopdf.scroll_up)
