package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopdf/internal/actions"
	"gopdf/internal/commands"
	"gopdf/internal/config"
)

func main() {
	check := flag.Bool("check", false, "check generated files without writing")
	flag.Parse()
	if err := config.ValidateReferenceMetadata(); err != nil {
		fatal(err)
	}
	luaRefs := config.LuaReferences()
	luaDocs, err := loadLuaFunctionDocs()
	if err != nil {
		fatal(err)
	}
	if err := validateLuaFunctionDocs(luaRefs, luaDocs); err != nil {
		fatal(err)
	}
	reference := renderReference(luaRefs, luaDocs)
	outputs := map[string][]byte{
		"docs/reference.md":  []byte(reference),
		"config.example.lua": []byte(renderExampleConfig()),
	}
	for path, content := range outputs {
		if *check {
			existing, err := os.ReadFile(path)
			if errors.Is(err, os.ErrNotExist) && path == "docs/reference.md" {
				// The application repository ignores the generated reference; the
				// documentation site generates it during its build.
				continue
			}
			if err != nil || !bytes.Equal(existing, content) {
				fatal(fmt.Errorf("%s is stale; run go generate ./...", path))
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fatal(err)
		}
	}
}

func renderReference(luaRefs []config.LuaReferenceEntry, luaDocs map[string]string) string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by go generate ./...; DO NOT EDIT. -->\n\n")
	b.WriteString("# Reference\n\n")
	b.WriteString("This page is generated from the same registries used by the application.\n\n")
	b.WriteString("## Configuration options\n\n")
	b.WriteString("Assign options with `gopdf.options.<name> = <value>` in Lua or `:set <name>=<value>` at runtime. Colors use `{ r, g, b }` in Lua and `r,g,b` or `#RRGGBB` with `:set`.\n\n")
	b.WriteString("| Option | Type | Default | Description |\n|---|---|---|---|\n")
	for _, ref := range config.OptionReferences() {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", markdownCode(ref.Name), ref.Type, markdownCode(ref.Default), ref.Description)
	}
	b.WriteString("\n## Commands\n\n")
	b.WriteString("| Command | Description |\n|---|---|\n")
	for _, ref := range commands.CommandReferences() {
		fmt.Fprintf(&b, "| %s | %s |\n", markdownCode(ref.Command), ref.Description)
	}
	b.WriteString("\nSearch flags: `-r` regular expression, `-i` ignore case, `-w` whole word, and `-p` current page only. Flags can be combined.\n")
	b.WriteString("\n## Lua functions\n\n")
	b.WriteString("The index below is followed by a detailed entry for every function. Lua errors are raised as protected-call errors; use `pcall` when a script should handle them without aborting the current dispatch.\n\n")
	b.WriteString("### Index\n\n| Function | Summary |\n|---|---|\n")
	for _, ref := range luaRefs {
		doc := luaDocs[luaDocumentationName(ref.Signature)]
		fmt.Fprintf(&b, "| %s | %s |\n", markdownCode(ref.Signature), docSummary(ref.Signature, doc))
	}
	for _, ref := range luaRefs {
		renderLuaFunction(&b, ref, luaDocs[luaDocumentationName(ref.Signature)])
	}
	b.WriteString("\n### UI views\n\n")
	b.WriteString("Create views with `local view = gopdf.ui.create(spec)`, then call `view:show()`. The specification supports `id`, `title`, `rows`, `selected`, `scroll`, `query`, `searchable`, `on_select`, and `on_close`. A row may be a string or a table with `text`, `value`, `id`, `secondary`, `depth`, and `disabled`.\n\n")
	b.WriteString("View methods are `show()`, `close()`, `visible()`, `set_rows(rows)`, `set_selected(index)`, `set_scroll(scroll)`, `set_query(query)`, `selected()`, `scroll()`, and `query()`. Selection indices are 1-based, with 0 meaning no selection. `on_select` receives `(index, value, text, id)`, preserving the original row index and ID when the list is filtered. `on_close` runs for user, programmatic, replacement, and document-close paths.\n")
	renderPortablePluginReference(&b)
	b.WriteString("\n## Bindable actions\n\n")
	b.WriteString("Every action is available as `gopdf.<action>`, can be passed to `gopdf.bind`, and can be called from a runtime Lua callback.\n\n")
	b.WriteString("| Action | Default keys | Countable |\n|---|---|---|\n")
	for _, action := range actions.All() {
		keys := make([]string, len(action.Keys))
		for i, key := range action.Keys {
			keys[i] = markdownCode(displayKey(key))
		}
		fmt.Fprintf(&b, "| %s | %s | %t |\n", markdownCode(action.Name), strings.Join(keys, ", "), action.Countable)
	}
	b.WriteString("\n## Lua tables\n\n")
	b.WriteString("- `gopdf.document`: `path`, `name`, `extension`, `exists`, `size_bytes`, and `page_count`.\n")
	b.WriteString("- `gopdf.status_bar`: `left`, `right`, and `visible`.\n")
	b.WriteString("- `gopdf.options`: all entries from the configuration-options table.\n")
	b.WriteString("- `gopdf.cache`, `gopdf.ui`, and `gopdf.plugin`: functions are listed above.\n")
	b.WriteString("\n### Status bar\n\n")
	b.WriteString("Set `gopdf.status_bar.visible` to a boolean to show or hide the status bar. Configure horizontal spacing with `gopdf.options.status_bar_padding` and text size with `gopdf.options.ui_font_size`. The `status_bar_left` and `status_bar_right` options are templates with these substitutions:\n\n")
	b.WriteString("| Placeholder | Value |\n|---|---|\n")
	b.WriteString("| `{message}` | Status message or active input prompt. |\n")
	b.WriteString("| `{page}` | Current physical page, or the page range for a dual-page spread. |\n")
	b.WriteString("| `{label}` | PDF page label, or the label range for a dual-page spread. |\n")
	b.WriteString("| `{total}` | Total physical page count. |\n")
	b.WriteString("| `{mode}` / `{fit}` | Current render mode and fit mode. |\n")
	b.WriteString("| `{rot}` / `{zoom}` | Clockwise rotation in degrees and zoom as a percentage. |\n")
	b.WriteString("| `{dual}` / `{cover}` | `dual` or `single`, and `cover` or `flat`. |\n")
	b.WriteString("| `{search}` | Current match counter, such as `[2/5]`, or empty when there is no current match. |\n")
	b.WriteString("| `{document}` | Document filename. |\n")
	b.WriteString("| `{input}` / `{prompt}` | Active input text and search prompt (`/` or `?`). |\n")
	b.WriteString("| `$$` | A literal dollar sign. |\n")
	return b.String()
}

func renderLuaFunction(b *strings.Builder, ref config.LuaReferenceEntry, doc string) {
	fmt.Fprintf(b, "\n### %s\n\n%s\n\n", markdownCode(ref.Signature), formatLuaDoc(ref.Signature, doc))
}

func renderExampleConfig() string {
	var b strings.Builder
	b.WriteString("-- Code generated by go generate ./...; DO NOT EDIT.\n")
	b.WriteString("-- All supported options and default bindings. Copy only values you want to change.\n\n")
	for _, ref := range config.OptionReferences() {
		fmt.Fprintf(&b, "gopdf.options.%s = %s -- %s\n", ref.Name, ref.Default, ref.Description)
	}
	b.WriteString("\n-- Default key bindings.\n\n")
	for _, action := range actions.All() {
		for _, key := range action.Keys {
			fmt.Fprintf(&b, "gopdf.bind(%q, gopdf.%s)\n", key, action.Name)
		}
	}
	b.WriteString("\n-- Default mouse bindings.\n\n")
	cfg := config.Default()
	events := make([]string, 0, len(cfg.MouseBindings))
	for event := range cfg.MouseBindings {
		events = append(events, event)
	}
	sort.Strings(events)
	for _, event := range events {
		fmt.Fprintf(&b, "gopdf.bind_mouse(%q, gopdf.%s)\n", event, cfg.MouseBindings[event])
	}
	return b.String()
}

func displayKey(key string) string {
	if key == " " {
		return "Space"
	}
	return key
}

func markdownCode(value string) string {
	value = html.EscapeString(value)
	value = strings.ReplaceAll(value, "|", "&#124;")
	return "<code>" + value + "</code>"
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
