package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopdf/internal/actions"
	"gopdf/internal/commands"
	"gopdf/internal/config"
	"gopdf/internal/keys"
)

func main() {
	check := flag.Bool("check", false, "check generated files without writing")
	flag.Parse()
	if err := config.ValidateReferenceMetadata(); err != nil {
		fatal(err)
	}
	luaRefs := config.LuaReferences()
	luaDocs, err := loadLuaFunctionDocs()
	if err != nil {
		fatal(err)
	}
	if err := validateLuaFunctionDocs(luaRefs, luaDocs); err != nil {
		fatal(err)
	}
	reference := renderReference(luaRefs, luaDocs)
	outputs := map[string][]byte{
		"docs/reference.md":  []byte(reference),
		"config.example.lua": []byte(renderExampleConfig()),
	}
	for path, content := range outputs {
		if *check {
			existing, err := os.ReadFile(path)
			if errors.Is(err, os.ErrNotExist) && path == "docs/reference.md" {
				// The application repository ignores the generated reference; the
				// documentation site generates it during its build.
				continue
			}
			if err != nil || !bytes.Equal(existing, content) {
				fatal(fmt.Errorf("%s is stale; run go generate ./...", path))
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fatal(err)
		}
	}
}

func renderReference(luaRefs []config.LuaReferenceEntry, luaDocs map[string]string) string {
	var b strings.Builder
	b.WriteString("<!-- Code generated by go generate ./...; DO NOT EDIT. -->\n\n")
	b.WriteString("# Reference\n\n")
	b.WriteString("This page is generated from the same registries used by the application.\n\n")
	b.WriteString("## Configuration options\n\n")
	b.WriteString("Assign options with `gopdf.options.<name> = <value>` in Lua or `:set <name>=<value>` at runtime. Colors use `{ r, g, b }` in Lua and `r,g,b` or `#RRGGBB` with `:set`.\n\n")
	b.WriteString("| Option | Type | Default | Description |\n|---|---|---|---|\n")
	for _, ref := range config.OptionReferences() {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", markdownCode(ref.Name), ref.Type, markdownCode(ref.Default), ref.Description)
	}
	renderThemeReference(&b)
	b.WriteString("\n## Commands\n\n")
	b.WriteString("| Command | Description |\n|---|---|\n")
	for _, ref := range commands.CommandReferences() {
		fmt.Fprintf(&b, "| %s | %s |\n", markdownCode(ref.Command), ref.Description)
	}
	b.WriteString("\nSearch flags:")
	for i, flag := range commands.SearchFlags() {
		sep := ","
		if i == 0 {
			sep = ""
		}
		fmt.Fprintf(&b, "%s `-%s` %s", sep, flag.Flag, flag.Description)
	}
	b.WriteString(". Flags can be combined.\n")
	b.WriteString("\n## Lua functions\n\n")
	b.WriteString("The index below is followed by a detailed entry for every function. Lua errors are raised as protected-call errors; use `pcall` when a script should handle them without aborting the current dispatch.\n\n")
	b.WriteString("### Index\n\n| Function | Summary |\n|---|---|\n")
	for _, ref := range luaRefs {
		doc := luaDocs[luaDocumentationName(ref.Signature)]
		fmt.Fprintf(&b, "| %s | %s |\n", markdownCode(ref.Signature), docSummary(ref.Signature, doc))
	}
	for _, ref := range luaRefs {
		renderLuaFunction(&b, ref, luaDocs[luaDocumentationName(ref.Signature)])
	}
	b.WriteString("\n### UI views\n\n")
	b.WriteString("Create views with `local view = gopdf.ui.create(spec)`, then call `view:show()`. The specification supports `id`, `title`, `rows`, `selected`, `scroll`, `query`, `searchable`, `on_select`, and `on_close`. A row may be a string or a table with `text`, `value`, `id`, `secondary`, `depth`, and `disabled`.\n\n")
	b.WriteString("View methods are `show()`, `close()`, `visible()`, `set_rows(rows)`, `set_selected(index)`, `set_scroll(scroll)`, `set_query(query)`, `selected()`, `scroll()`, and `query()`. Selection indices are 1-based, with 0 meaning no selection. `on_select` receives `(index, value, text, id)`, preserving the original row index and ID when the list is filtered. `on_close` runs for user, programmatic, replacement, and document-close paths.\n")
	renderPortablePluginReference(&b)
	renderBindingNames(&b)
	b.WriteString("\n## Bindable actions\n\n")
	b.WriteString("Every action is available as `gopdf.<action>`, can be passed to `gopdf.bind`, and can be called from a runtime Lua callback.\n\n")
	b.WriteString("| Action | Default keys | Countable |\n|---|---|---|\n")
	for _, action := range actions.All() {
		keys := make([]string, len(action.Keys))
		for i, key := range action.Keys {
			keys[i] = markdownCode(key)
		}
		fmt.Fprintf(&b, "| %s | %s | %t |\n", markdownCode(action.Name), strings.Join(keys, ", "), action.Countable)
	}
	b.WriteString("\n## Lua tables\n\n")
	b.WriteString("- `gopdf.document`: `path`, `name`, `extension`, `exists`, `size_bytes`, and `page_count`.\n")
	b.WriteString("- `gopdf.options` (alias `gopdf.o`): all entries from the configuration-options table.\n")
	b.WriteString("- `gopdf.theme`: the theme; see [Theme](#theme). Read or assign whole, or one field at a time.\n")
	b.WriteString("- `gopdf.themes`: each built-in theme as a fresh table, such as `gopdf.themes.birch`.\n")
	b.WriteString("- `gopdf.cache`, `gopdf.ui`, and `gopdf.plugin`: functions are listed above.\n")
	b.WriteString("\n### Status bar\n\n")
	b.WriteString("Show or hide the status bar with `gopdf.options.status_bar_visible`. Its look comes from the theme: `status_bar_style` places it along the bottom or floating as pills, `status_bar_padding` sets its horizontal spacing and `font.size` its text size, and the `status`, `status_left` and `status_right` elements style it further. The `status_bar_left` and `status_bar_right` options are templates with these substitutions:\n\n")
	b.WriteString("| Placeholder | Value |\n|---|---|\n")
	b.WriteString("| `{message}` | Status message or active input prompt. |\n")
	b.WriteString("| `{page}` | Current physical page, or the page range for a dual-page spread. |\n")
	b.WriteString("| `{label}` | PDF page label, or the label range for a dual-page spread. |\n")
	b.WriteString("| `{total}` | Total physical page count. |\n")
	b.WriteString("| `{mode}` / `{fit}` | Current render mode and fit mode. |\n")
	b.WriteString("| `{rot}` / `{zoom}` | Clockwise rotation in degrees and zoom as a percentage. |\n")
	b.WriteString("| `{dual}` / `{cover}` | `dual` or `single`, and `cover` or `flat`. |\n")
	b.WriteString("| `{search}` | Current match counter, such as `[2/5]`, or empty when there is no current match. |\n")
	b.WriteString("| `{document}` | Document filename. |\n")
	b.WriteString("| `{modified}` | `[+] ` while the document has unsaved edits, else empty. |\n")
	b.WriteString("| `{input}` / `{prompt}` | Active input text and search prompt (`/` or `?`). |\n")
	b.WriteString("| `$$` | A literal dollar sign. |\n")
	return b.String()
}

// renderBindingNames describes the key and mouse names that bindings accept.
// The tables come from the keys package, which parses those names.
func renderBindingNames(b *strings.Builder) {
	b.WriteString("\n## Key and mouse names\n\n")
	b.WriteString("`gopdf.bind` and `gopdf.unbind` take a key sequence; `gopdf.bind_mouse` and `gopdf.unbind_mouse` take a mouse event. An unknown name is an error. To find the name of a key, bind it in `:keybinds`, which records the keys you press.\n\n")

	b.WriteString("### Keys\n\n")
	b.WriteString("A sequence is one or more keys written one after another, such as `gg`, `g?` or `<C-w>j`. Each key must follow the one before within `sequence_timeout_ms`. Digits 1 to 9 start a count, as in `5j` or `12g`, and `'` and `\"` jump to and set marks, so binding a sequence that begins with any of them is an error.\n\n")
	b.WriteString("Printable keys are written as the character they type with the current keyboard layout, so on a US keyboard Shift+1 is `!`. Letters are case-sensitive: `J` is Shift+j, or j with Caps Lock on. On layouts without Latin letters, letter keys are read as their QWERTY letters. Write `<` as `<lt>`.\n\n")
	b.WriteString("Other keys are written by name in angle brackets. Names are case-insensitive.\n\n")
	b.WriteString("| Name | Key |\n|---|---|\n")
	var names, aliases []string
	named := keys.NamedKeys()
	for i, key := range named {
		names = append(names, "`<"+key.Name+">`")
		for _, alias := range key.Aliases {
			aliases = append(aliases, "`<"+alias+">`")
		}
		if i+1 < len(named) && named[i+1].Description == key.Description {
			continue
		}
		description := key.Description
		if len(aliases) > 0 {
			description = strings.TrimSuffix(description, ".") + "; also " + joinWords(aliases, "and") + "."
		}
		fmt.Fprintf(b, "| %s | %s |\n", nameRange(names), description)
		names, aliases = nil, nil
	}

	b.WriteString("\n### Modifiers\n\n")
	b.WriteString("Modifiers go inside the brackets before the key name, as in `<C-p>`, `<C-S-Tab>` or `<D-c>`.\n\n")
	b.WriteString("| Prefix | Modifier |\n|---|---|\n")
	b.WriteString("| `C-` | Ctrl. |\n")
	b.WriteString("| `D-` | Cmd on macOS; the Super or Windows key elsewhere. |\n")
	b.WriteString("| `S-` | Shift. |\n\n")
	b.WriteString("Ctrl and Cmd combine with any key: letters, digits, symbols and the names above, as in `<C-a>`, `<C-=>`, `<C-Space>` or `<D-Up>`. With them, a key is named by its unshifted character and Shift is written out: `<C-S-r>` is Ctrl+Shift+r, `<C-S-1>` is Ctrl+Shift+1, and `<C-R>` is Ctrl+r. Write `>` as `<gt>` after a modifier, as in `<C-gt>`. Without Ctrl or Cmd, Shift applies to named keys, as in `<S-Tab>` or `<S-F5>`, and `<S-j>` means `J`; for other printable keys, write the shifted character. Alt is not a modifier: a key pressed with Alt runs no binding.\n\n")
	b.WriteString("Modifiers may be written in any order, so `<C-S-Tab>`, `<s-c-tab>` and `<S-C-TAB>` are the same key. Bindings are stored and shown in the first form.\n\n")

	b.WriteString("### Mouse events\n\n")
	b.WriteString("| Event | Fires on |\n|---|---|\n")
	events := keys.MouseEvents()
	names = nil
	for i, event := range events {
		names = append(names, "`"+event.Name+"`")
		if i+1 < len(events) && events[i+1].Description == event.Description {
			continue
		}
		fmt.Fprintf(b, "| %s | %s |\n", strings.Join(names, ", "), event.Description)
		names = nil
	}
	b.WriteString("\nButton events take no modifiers, and the horizontal wheel does nothing while Ctrl is held. Event names are case-insensitive and may be written in angle brackets like keys: `<middle_down>` is `middle_down`. `-` may be written for `_`, and `ctrl_wheel_up` is the same as `<C-wheel_up>`.\n\n")
	b.WriteString("A bound button event replaces that button's built-in behaviour, such as text selection and following links on the left button. Wheel directions scroll smoothly only while they are bound to their default scroll actions.\n")
}

// nameRange lists names, shortening a numbered run such as F1 to F24 to
// its first and last.
func nameRange(names []string) string {
	if len(names) > 5 {
		return names[0] + " to " + names[len(names)-1]
	}
	return strings.Join(names, ", ")
}

// joinWords joins items as prose, as in "a, b and c".
func joinWords(items []string, conjunction string) string {
	if len(items) == 1 {
		return items[0]
	}
	return strings.Join(items[:len(items)-1], ", ") + " " + conjunction + " " + items[len(items)-1]
}

func renderLuaFunction(b *strings.Builder, ref config.LuaReferenceEntry, doc string) {
	fmt.Fprintf(b, "\n### %s\n\n%s\n\n", markdownCode(ref.Signature), formatLuaDoc(ref.Signature, doc))
}

func renderExampleConfig() string {
	var b strings.Builder
	b.WriteString("-- Code generated by go generate ./...; DO NOT EDIT.\n")
	b.WriteString("-- All supported options and default bindings. Copy only values you want to change.\n\n")
	for _, ref := range config.OptionReferences() {
		fmt.Fprintf(&b, "gopdf.options.%s = %s -- %s\n", ref.Name, ref.Default, ref.Description)
	}
	// The theme is left commented out: assigned whole, it would replace the
	// theme chosen with :theme in every config copied from this one.
	b.WriteString("\n-- The theme, with each field's default. Pick one with :theme. Assigning gopdf.theme\n")
	b.WriteString("-- whole replaces the theme picked, so set the fields you want to change one at a\n")
	b.WriteString("-- time, as gopdf.theme.accent = \"#335533\" does, and they change whichever is picked.\n\n")
	var theme strings.Builder
	renderExampleTheme(&theme)
	for _, line := range strings.SplitAfter(theme.String(), "\n") {
		if line != "" {
			b.WriteString("-- " + line)
		}
	}
	b.WriteString("\n-- Default key bindings.\n\n")
	for _, action := range actions.All() {
		for _, key := range action.Keys {
			fmt.Fprintf(&b, "gopdf.bind(%q, gopdf.%s)\n", key, action.Name)
		}
	}
	b.WriteString("\n-- Default mouse bindings.\n\n")
	cfg := config.Default()
	events := make([]string, 0, len(cfg.MouseBindings))
	for event := range cfg.MouseBindings {
		events = append(events, event)
	}
	sort.Strings(events)
	for _, event := range events {
		fmt.Fprintf(&b, "gopdf.bind_mouse(%q, gopdf.%s)\n", event, cfg.MouseBindings[event])
	}
	return b.String()
}

// renderThemeReference documents the theme table and its presets.
func renderThemeReference(b *strings.Builder) {
	b.WriteString("\n## Theme\n\n")
	b.WriteString("The theme is everything about how the viewer looks: its colours, UI font and the shape of its panels. Assign it as one table, so a theme can be shared as a single table:\n\n")
	b.WriteString("```lua\ngopdf.theme = {\n  base = \"birch\",  -- start from a built-in theme; the default is " + config.DefaultTheme + "\n  accent = \"#335533\",\n  alt = { accent = \"#88aa88\" },\n  font = { family = \"Iosevka\", size = 14 },\n}\n```\n\n")
	b.WriteString("`require` searches the configuration file's directory first, so a theme can live in a file of its own beside `config.lua`. Have it return its table, as `themes/forest.lua` holding `return { accent = \"#2f5d3a\" }`, and apply it with `gopdf.theme = require(\"themes.forest\")`; dots in the name are directories, and `require(\"forest\")` would load `forest.lua`.\n\n")
	b.WriteString("`:theme` lists the built-in themes and the theme files, each named for its file: those in `themes/` beside `config.lua`, then those in each directory plugins are searched for with `themes` in place of `plugins`, as `/usr/lib/gopdf/themes` and `~/.config/gopdf/themes` on Linux. Where two directories have a file of the same name, the first wins. `:theme` shows each one as it is selected: Enter keeps it, Esc puts back the theme before, and `:theme <name>` switches straight to one. A file named for a built-in theme is left out. The theme chosen is remembered and applied before `config.lua` runs, so what `config.lua` changes field by field, as `gopdf.theme.accent = \"#335533\"` does, changes the chosen theme too; assigning `gopdf.theme` whole replaces it, and `:theme` then says that a theme it picks lasts only until gopdf restarts.\n\n")
	b.WriteString("Fields left out keep the base theme's values. Assign a preset by name with `gopdf.theme = \"birch\"`, or a single field with `gopdf.theme.accent = \"#335533\"`; at runtime use `:set theme=birch` or `:set theme.accent=#335533`. Built-in themes: " + codeList(config.ThemeNames()) + ". `gopdf.themes.<name>` gives a copy of one to change. Fields and element properties this version does not know are skipped with a warning, so a theme written for a newer version still loads; `:set` refuses them.\n\n")
	b.WriteString("Colours are `\"#RRGGBB\"` or `{ r, g, b }`. The `alt` table holds the colours used in alternate-color mode, toggled with `:colors`, and has the same colour fields as the theme. The `font` table picks the UI font; with neither `family` nor `path` set it is the system's interface font.\n\n")
	b.WriteString("The `motion` table sets how the UI moves. Each transition is written as CSS writes one, a duration and an easing such as `\"140ms ease-out\"`, or as `{ duration = 140, easing = \"ease-out\" }`; easings are `linear`, `ease`, `ease-in`, `ease-out`, `ease-in-out` and `cubic-bezier(x1, y1, x2, y2)`, and `\"none\"` turns one transition off. By default only what moves is animated: the selection, the cursor and the sides of the status bar glide to where they go, while menus and messages appear and go at once; give `panel` or `message` a transition to fade them. `scale` slows or speeds every transition, and `0` turns motion off altogether, as the classic theme does.\n\n")
	b.WriteString("| Field | Type | Default | Description |\n|---|---|---|---|\n")
	for _, ref := range config.ThemeReferences() {
		fmt.Fprintf(b, "| %s | %s | %s | %s |\n", markdownCode(ref.Name), ref.Type, markdownCode(ref.Default), ref.Description)
	}
	renderElementReference(b)
}

// renderElementReference documents the elements table, its properties and
// the shapes it can draw.
func renderElementReference(b *strings.Builder) {
	b.WriteString("\n### Elements\n\n")
	b.WriteString("Each piece of the UI is an element with a style of its own, which the theme's `elements` table changes. The fields above still shape every element: an element's style starts from the theme's `radius`, `padding`, `shadow` and `status_bar_style`, and from the element it inherits from, and the properties set here go over that.\n\n")
	b.WriteString("```lua\ngopdf.theme = {\n  elements = {\n    panel = { radius = 12, shadow = \"0 8 24 shadow\" },\n    row_selected = { fill = \"accent\", text = \"panel\" },\n    status_left = { shape = \"pill\" },\n  },\n}\n```\n\n")
	b.WriteString("Set one property with `gopdf.theme.elements.panel.radius = 12`, or at runtime with `:set theme.elements.panel.radius=12`. Reading a property gives the value in effect, and assigning `nil` returns it to its default. The `status_bar_style` field picks the defaults of `status`, `status_left` and `status_right`: `bar` lays a bar along the bottom of the window, and `pill` floats a pill for each side over the page.\n\n")
	b.WriteString("Colours name a palette colour, which follows the color mode, or are `\"#RRGGBB\"`, `\"#RRGGBBAA\"` or `\"none\"`; any can be followed by an opacity percentage, as `\"accent/16\"`. The name `shadow` is black at the strength shadows need over the background. Lengths are logical pixels, scaled on high-density displays.\n\n")
	b.WriteString("| Property | Type | Description |\n|---|---|---|\n")
	for _, ref := range config.StylePropertyReferences() {
		fmt.Fprintf(b, "| %s | %s | %s |\n", markdownCode(ref.Name), ref.Type, ref.Description)
	}
	b.WriteString("\nEvery element starts from `" + config.BaseStyleReference() + "`. The elements, with what their styles change from that in the default theme:\n\n")
	b.WriteString("| Element | Description | Properties | Default style |\n|---|---|---|---|\n")
	for _, ref := range config.ElementReferences() {
		description := ref.Description
		if ref.Inherits != "" {
			description += " Starts from " + markdownCode(ref.Inherits) + "."
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s |\n", markdownCode(ref.Name), description, strings.Join(ref.Properties, ", "), markdownCode(ref.Defaults))
	}
	b.WriteString("\n#### Shapes\n\n")
	b.WriteString("A `rect` has its corners rounded by `radius`, and a `pill` has round ends whatever its size. Any other shape is a path, given as SVG path data or drawn by a Lua function. The border is drawn inside the shape's edge, and shadows follow the shape.\n\n")
	b.WriteString("Path data takes the commands `M`, `L`, `H`, `V`, `Q`, `C` and `Z`, lowercase for relative coordinates. A coordinate is in logical pixels from the box's top left, or a percentage of the box's width or height, offset by pixels written straight after it. This arrow points right whatever the row's width:\n\n")
	b.WriteString("```lua\ngopdf.theme.elements.row_selected.shape = \"M0,0 H100%-8 L100%,50% L100%-8,100% H0 Z\"\n```\n\n")
	b.WriteString("A function is called as `shape(path, w, h)` with the box's size in logical pixels, whenever an element is drawn at a size not drawn before. Its `path` has the methods `move_to(x, y)`, `line_to(x, y)`, `quad_to(cx, cy, x, y)`, `cubic_to(c1x, c1y, c2x, c2y, x, y)`, `close()`, `rect(x, y, w, h [, radius])` and `ellipse(cx, cy, rx [, ry])`, each returning `path`. If a shape fails, its element is drawn as a plain rect and the error is reported once.\n\n")
	b.WriteString("```lua\ngopdf.theme.elements.status_left.shape = function(path, w, h)\n  path:move_to(h / 2, 0):line_to(w, 0):line_to(w - h / 2, h):line_to(0, h):close()\nend\n```\n")
	b.WriteString("\n#### Drawing\n\n")
	b.WriteString("An element's `draw` function draws its box in place of the default drawing, as `draw(canvas, box, state)`, each time the element is drawn; its text is drawn over it as usual. `box` holds the box's `x`, `y`, `w` and `h` in logical pixels from the window's top left, and `state` the `element` being drawn, whether `alt` colours are on, and the `time` in seconds since gopdf started, for drawing that moves, so a function set on `row` can tell `row_selected` apart. Both tables are reused from call to call, so copy what you keep. Like other properties, a draw function carries to the elements that start from its element; assigning `false` or `nil` removes it.\n\n")
	b.WriteString("The canvas's coordinates are logical pixels from the box's top left, and may reach outside it. Its methods are:\n\n")
	b.WriteString("| Method | Draws |\n|---|---|\n")
	for _, row := range [][2]string{
		{"canvas:default()", "The element as it would be drawn without the function: its box, or the loader's drops and the autoscroll marker."},
		{"canvas:fill(path, color)", "The inside of a path: path data as a shape takes, or a path from `canvas:path()`."},
		{"canvas:stroke(path, color [, width])", "A line along a path, 1 logical pixel wide unless given, with round joins."},
		{"canvas:rect(x, y, w, h, color [, radius])", "A rect, its corners rounded by radius."},
		{"canvas:text(x, y, text, color [, bold])", "Text with the top of its line at y, in the UI font; returns its width."},
		{"canvas:measure(text [, bold])", "Nothing; returns the width and line height of text."},
		{"canvas:path()", "Nothing; returns an empty path, with the methods a shape function's path has."},
	} {
		fmt.Fprintf(b, "| %s | %s |\n", markdownCode(row[0]), row[1])
	}
	b.WriteString("\nColours are written as in the elements table, and the element's `opacity` applies to them. Panels and the link preview draw their border over their contents, which they do only when the function called `canvas:default()`. If the function fails, the element is drawn as it would be without it, the error is reported once, and the function is not called again until the configuration changes.\n\n")
	b.WriteString("```lua\ngopdf.theme.elements.row_selected.draw = function(canvas, box, state)\n  canvas:default()\n  canvas:rect(0, 5, 3, box.h - 10, \"accent\", 1.5) -- a bar at the left\nend\n```\n")
}

// renderExampleTheme writes the default theme as a gopdf.theme table.
func renderExampleTheme(b *strings.Builder) {
	fmt.Fprintf(b, "gopdf.theme = {\n  base = %q,\n", config.DefaultTheme)
	group := ""
	for _, ref := range config.ThemeReferences() {
		name, member, nested := strings.Cut(ref.Name, ".")
		if !nested {
			name, member = "", name
		}
		if name != group {
			if group != "" {
				b.WriteString("  },\n")
			}
			if name != "" {
				fmt.Fprintf(b, "  %s = {\n", name)
			}
			group = name
		}
		indent := "  "
		if group != "" {
			indent = "    "
		}
		fmt.Fprintf(b, "%s%s = %s, -- %s\n", indent, member, ref.Default, ref.Description)
	}
	if group != "" {
		b.WriteString("  },\n")
	}
	b.WriteString("  elements = {}, -- The style of each piece of the UI, such as panel or row_selected; see Elements in the reference.\n")
	b.WriteString("}\n")
}

func markdownCode(value string) string {
	value = html.EscapeString(value)
	value = strings.ReplaceAll(value, "|", "&#124;")
	return "<code>" + value + "</code>"
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
