package config

import "gopdf/internal/actions"

func Default() Config {
	return Config{
		StatusBarVisible:    true,
		RenderMode:          "continuous",
		RenderOversample:    1,
		PageCacheSize:       16,
		DualPage:            false,
		FirstPageOffset:     true,
		FitMode:             "page",
		AnchorPosition:      "center",
		Background:          [3]uint8{220, 220, 220},
		PageBackground:      [3]uint8{255, 255, 255},
		Foreground:          [3]uint8{20, 20, 20},
		StatusBarColor:      [3]uint8{220, 220, 220},
		AltBackground:       [3]uint8{20, 20, 20},
		AltPageBackground:   [3]uint8{17, 17, 17},
		AltForeground:       [3]uint8{255, 255, 255},
		AltStatusBarColor:   [3]uint8{20, 20, 20},
		HighlightForeground: [3]uint8{0, 0, 0},
		HighlightBackground: [3]uint8{255, 224, 102},
		AltColors:           false,
		PageGap:             0,
		SpreadGap:           0,
		PageGapVertical:     0,
		PageGapHorizontal:   0,
		ScrollStep:          64,
		StatusBarHeight:     28,
		StatusBarPadding:    8,
		UIFontSize:          14,
		UIFontPath:          "",
		StatusBarLeft:       "{message}",
		StatusBarRight:      "{page}/{total} {mode} fit={fit} rot={rot} {zoom}",
		SequenceTimeoutMS:   700,
		NormalMessage:       "",
		KeyBindings:         actions.DefaultBindings(),
		MouseBindings: map[string]string{
			"wheel_up":       "scroll_up",
			"wheel_down":     "scroll_down",
			"wheel_left":     "scroll_left",
			"wheel_right":    "scroll_right",
			"<c-wheel_up>":   "zoom_in",
			"<c-wheel_down>": "zoom_out",
			"middle_down":    "pan",
		},
		MouseTextSelect:      true,
		NaturalScroll:        false,
		SessionDatabase:      true,
		AntiAliasing:         8,
		OutlineInitialDepth:  1,
		OutlineWidthPercent:  70,
		OutlineHeightPercent: 80,
		CompletionMaxItems:   10,
		RecentFilesMax:       10,
	}
}
