package config

import (
	"os"
	"path/filepath"
	"testing"
)

// openKeybindRuntime opens a runtime with the config at dir/config.lua.
func openKeybindRuntime(t *testing.T, dir string, options OpenOptions) *Runtime {
	t.Helper()
	rt, err := OpenWithOptions(filepath.Join(dir, "config.lua"), "", options)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(rt.Close)
	return rt
}

func TestKeybindingsChangedInTheViewerAreKept(t *testing.T) {
	setTestDataDir(t)
	dir := t.TempDir()
	rt := openKeybindRuntime(t, dir, OpenOptions{})
	if err := rt.SetKeyBinding("<c-enter>", "quit"); err != nil {
		t.Fatal(err)
	}
	if err := rt.RebindKey("gg", "<C-g>", "first_page"); err != nil {
		t.Fatal(err)
	}
	if err := rt.UnbindKey("q"); err != nil {
		t.Fatal(err)
	}

	for _, rt := range []*Runtime{rt, openKeybindRuntime(t, dir, OpenOptions{})} {
		if err := rt.Reload(); err != nil {
			t.Fatal(err)
		}
		bindings := rt.Config().KeyBindings
		if bindings["<C-CR>"] != "quit" || bindings["<C-g>"] != "first_page" {
			t.Fatalf("bound keys not kept: <C-CR>=%q <C-g>=%q", bindings["<C-CR>"], bindings["<C-g>"])
		}
		if action, ok := bindings["gg"]; ok {
			t.Fatalf("rebound gg still runs %q", action)
		}
		if action, ok := bindings["q"]; ok {
			t.Fatalf("unbound q still runs %q", action)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "autogen.lua")); !os.IsNotExist(err) {
		t.Fatalf("autogen.lua written: %v", err)
	}
}

func TestConfigOutranksStoredKeybindings(t *testing.T) {
	setTestDataDir(t)
	dir := t.TempDir()
	rt := openKeybindRuntime(t, dir, OpenOptions{})
	if err := rt.SetKeyBinding("<C-g>", "quit"); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "config.lua"), []byte(`gopdf.bind("<C-g>", gopdf.first_page)`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := rt.Reload(); err != nil {
		t.Fatal(err)
	}
	if got := rt.Config().KeyBindings["<C-g>"]; got != "first_page" {
		t.Fatalf("<C-g> = %q, want config.lua's first_page", got)
	}
	// Without a config, stored keybindings are not read either.
	if got, want := openKeybindRuntime(t, dir, OpenOptions{NoConfig: true}).Config().KeyBindings["<C-g>"], Default().KeyBindings["<C-g>"]; got != want {
		t.Fatalf("--no-config <C-g> = %q, want the default %q", got, want)
	}
}

func TestAutogenIsImportedOnce(t *testing.T) {
	setTestDataDir(t)
	dir := t.TempDir()
	// A key already stored keeps its binding over the file's.
	if err := storeKeyBindings(map[string]string{"<C-x>": "first_page"}); err != nil {
		t.Fatal(err)
	}
	autogen := `-- This file is generated by gopdf. Manual edits may be overwritten.
gopdf.bind("<keypad-1>", gopdf.quit)
gopdf.unbind("<c-keycode-45>")
gopdf.bind("<C-CR>", gopdf.quit)
gopdf.bind("<C-y>", "sample.greet")
gopdf.bind("<C-x>", gopdf.quit)
gopdf.unbind("q")
print("not written by gopdf")
`
	path := filepath.Join(dir, "autogen.lua")
	if err := os.WriteFile(path, []byte(autogen), 0o644); err != nil {
		t.Fatal(err)
	}

	bindings := openKeybindRuntime(t, dir, OpenOptions{}).Config().KeyBindings
	if bindings["<C-CR>"] != "quit" || bindings["<C-y>"] != "sample.greet" || bindings["<C-x>"] != "first_page" {
		t.Fatalf("imported <C-CR>=%q <C-y>=%q <C-x>=%q", bindings["<C-CR>"], bindings["<C-y>"], bindings["<C-x>"])
	}
	if _, ok := bindings["q"]; ok {
		t.Fatal("q is still bound")
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("autogen.lua left in place: %v", err)
	}
	if _, err := os.Stat(path + ".bak"); err != nil {
		t.Fatalf("autogen.lua not renamed: %v", err)
	}
	// Keys this version cannot read are dropped rather than kept.
	stored, err := storedKeyBindings()
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := stored["<keypad-1>"]; ok {
		t.Fatalf("unreadable key kept: %v", stored)
	}
	// The file is gone, so the next start reads the database alone.
	if got := openKeybindRuntime(t, dir, OpenOptions{}).Config().KeyBindings["<C-CR>"]; got != "quit" {
		t.Fatalf("after import <C-CR> = %q", got)
	}
}
