package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopdf/internal/actions"
)

func (r *Runtime) SetKeyBinding(key, action string) error {
	if !isBuiltinAction(action) {
		return fmt.Errorf("cannot persist non-builtin action %q", action)
	}
	r.setKeyBinding(key, action)
	return r.WriteAutogen()
}

func (r *Runtime) RebindKey(oldKey, newKey, action string) error {
	if !isBuiltinAction(action) {
		return fmt.Errorf("cannot persist non-builtin action %q", action)
	}
	if oldKey != "" && oldKey != newKey {
		r.unbindKey(oldKey)
	}
	r.setKeyBinding(newKey, action)
	return r.WriteAutogen()
}

func (r *Runtime) UnbindKey(key string) error {
	r.unbindKey(key)
	return r.WriteAutogen()
}

func (r *Runtime) WriteAutogen() error {
	path := r.autogenPath()
	if path == "" {
		return fmt.Errorf("autogen path unavailable")
	}
	data := generatedKeybindLua(r.cfg.KeyBindings)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(data), 0644); err != nil {
		return err
	}
	r.cfg.AutogenPath = path
	return nil
}

func generatedKeybindLua(bindings map[string]string) string {
	defaults := defaultBindings()
	keys := make([]string, 0, len(defaults)+len(bindings))
	seen := map[string]struct{}{}
	for key := range defaults {
		keys = append(keys, key)
		seen[key] = struct{}{}
	}
	for key := range bindings {
		if _, ok := seen[key]; !ok {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("-- This file is generated by gopdf. Manual edits may be overwritten.\n")
	for _, key := range keys {
		current, ok := bindings[key]
		def, isDefault := defaults[key]
		if !ok {
			if isDefault {
				fmt.Fprintf(&b, "gopdf.unbind(%q)\n", key)
			}
			continue
		}
		if isDefault && current == def {
			continue
		}
		if !isBuiltinAction(current) {
			continue
		}
		fmt.Fprintf(&b, "gopdf.bind(%q, gopdf.%s)\n", key, current)
	}
	return b.String()
}

func isBuiltinAction(action string) bool {
	return actions.IsBuiltin(action)
}

func Actions() []string {
	return actions.Names()
}

func defaultBindings() map[string]string {
	return map[string]string{
		"j":       "scroll_down",
		"<Down>":  "scroll_down",
		"k":       "scroll_up",
		"<Up>":    "scroll_up",
		"h":       "scroll_left",
		"<Left>":  "scroll_left",
		"l":       "scroll_right",
		"<Right>": "scroll_right",
		"J":       "next_page",
		"K":       "prev_page",
		" ":       "next_page",
		"<PgDn>":  "next_page",
		"<PgUp>":  "prev_page",
		"gg":      "first_page",
		"G":       "last_page",
		":":       "command_mode",
		"/":       "search_prompt",
		"?":       "search_prompt_backward",
		"n":       "search_next",
		"N":       "search_prev",
		"d":       "toggle_dual_page",
		"m":       "toggle_render_mode",
		"<C-r>":   "toggle_alt_colors",
		"co":      "toggle_first_page_offset",
		"<C-n>":   "toggle_status_bar",
		"f":       "toggle_fullscreen",
		"o":       "outline",
		"<CR>":    "confirm",
		"<Tab>":   "show_completion",
		"<S-Tab>": "prev_completion",
		"+":       "zoom_in",
		"=":       "zoom_in",
		"-":       "zoom_out",
		"0":       "reset_zoom",
		"w":       "fit_width",
		"z":       "fit_page",
		"r":       "rotate_cw",
		"R":       "rotate_ccw",
		"<C-g>":   "goto_page_prompt",
		"q":       "quit",
		"<Esc>":   "close",
		"<C-i>":   "jump_forward",
		"<C-o>":   "jump_backward",
		"<C-S-o>": "open_file_picker",
		"<F1>":    "keybinds",
		"<C-S-r>": "reload_config",
	}
}
