package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopdf/internal/actions"
)

func (r *Runtime) SetKeyBinding(key, action string) error {
	if !isBuiltinAction(action) {
		return fmt.Errorf("cannot persist non-builtin action %q", action)
	}
	r.setKeyBinding(key, action)
	return r.WriteAutogen()
}

func (r *Runtime) RebindKey(oldKey, newKey, action string) error {
	if !isBuiltinAction(action) {
		return fmt.Errorf("cannot persist non-builtin action %q", action)
	}
	if oldKey != "" && oldKey != newKey {
		r.unbindKey(oldKey)
	}
	r.setKeyBinding(newKey, action)
	return r.WriteAutogen()
}

func (r *Runtime) UnbindKey(key string) error {
	r.unbindKey(key)
	return r.WriteAutogen()
}

func (r *Runtime) WriteAutogen() error {
	path := r.autogenPath()
	if path == "" {
		return fmt.Errorf("autogen path unavailable")
	}
	data := generatedKeybindLua(r.cfg.KeyBindings)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(data), 0644); err != nil {
		return err
	}
	r.cfg.AutogenPath = path
	return nil
}

func generatedKeybindLua(bindings map[string]string) string {
	defaults := actions.DefaultBindings()
	keys := make([]string, 0, len(defaults)+len(bindings))
	seen := map[string]struct{}{}
	for key := range defaults {
		keys = append(keys, key)
		seen[key] = struct{}{}
	}
	for key := range bindings {
		if _, ok := seen[key]; !ok {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("-- This file is generated by gopdf. Manual edits may be overwritten.\n")
	for _, key := range keys {
		current, ok := bindings[key]
		def, isDefault := defaults[key]
		if !ok {
			if isDefault {
				fmt.Fprintf(&b, "gopdf.unbind(%q)\n", key)
			}
			continue
		}
		if isDefault && current == def {
			continue
		}
		if !isBuiltinAction(current) {
			continue
		}
		fmt.Fprintf(&b, "gopdf.bind(%q, gopdf.%s)\n", key, current)
	}
	return b.String()
}

func isBuiltinAction(action string) bool {
	return actions.IsBuiltin(action)
}

func Actions() []string {
	return actions.Names()
}
